### ISSUE TITLE
RDFS和关系型数据库

### ISSUE THREAD

**Issue by lknan** [SimmerChan/KG-demo-for-movie#11]
看了你的CSDN中的文章后受益匪浅，也有一些疑问。
RDFS查询语言SPARQL，和mysql查询语言，哪一个效率更高一点，速度更快一点。
RDFS感觉上和mysql一样是个数据库，只不过语法不同而已

**Comment by SimmerChan** [comment]
RDFS不是数据库，你可以类比mysql的schema，ER图之类的。SPARQL和SQL都是DSL，效率没办法直接比较，因为查询目标不同。

**Comment by lknan** [comment]
sparql查询rdfs的数据，也可以用sql查询数据库得到，我现在不知道最区别是什么，除了推理机外，对这个的接触，就是看完了你的那几篇文章




| |
17629011006
邮箱：17629011006@163.com
|

Signature is customized by Netease Mail Master

在2018年09月05日 12:00，SimmerChan 写道：

RDFS不是数据库，你可以类比mysql的schema，ER图之类的。SPARQL和SQL都是DSL，效率没办法直接比较，因为查询目标不同。
