### ISSUE TITLE
老哥， 见一个 py_3.X 的分支，给我权限。我提交一下代码

### ISSUE THREAD

**Issue by jiangzhonglian** [SimmerChan/KG-demo-for-movie#18]
我线下可以正常运行，没问题
![image](https://user-images.githubusercontent.com/9199175/54904432-7cea0900-4f19-11e9-9c75-8887ad83759b.png)

**Comment by BrambleXu** [comment]
顺便也把requirements.txt里的版本号写上吧

**Comment by jiangzhonglian** [comment]
额， pip install 最新的就行。。

**Comment by jiangzhonglian** [comment]
如果急着想用的！
3.x 版本地址：https://github.com/jiangzhonglian/KG-demo-for-movie

**Comment by cnxiekun** [comment]
> 如果急着想用的！
> 3.x 版本地址：https://github.com/jiangzhonglian/KG-demo-for-movie

老哥，运行起来了，但结果不对啊。“周星驰是谁啊” -- I don't know。。。。

**Comment by jiangzhonglian** [comment]
等服务器启动后在管理后台上传数据 kg_demo_movie.nt。 你再试试

**Comment by cnxiekun** [comment]
> 等服务器启动后在管理后台上传数据 kg_demo_movie.nt。 你再试试，它应该就知道了

谢谢指点。

![image](https://user-images.githubusercontent.com/21699650/57747071-7ea89f80-7706-11e9-82f4-500d19cc7618.png)
不过老哥你看我的截图，好像好些问题都没法回答啊，这个跟原博主发的帖子矛盾啊，这些问题他那边是可以的。你的代码能跑出结果吗?

**Comment by SimmerChan** [comment]
@jiangzhonglian 好的，我弄一下，麻烦了
