### ISSUE TITLE
from crawler.tradition2simple import traditional2simple这个包是如何安装的？

### ISSUE THREAD

**Issue by asdliuquan** [SimmerChan/KG-demo-for-movie#2]
在运行爬去数据的时候，使用的是python2.7，请问是如何安装crawler.tradition2simple呢？我尝试使用pip安装不成功。

**Comment by MartinHero** [comment]
同问啊，我用的python3也一直导不进去，有没有导进去的同学教一下，谢谢了

**Comment by Dartagnann** [comment]
导不进去包+1，python2.7

**Comment by c123853648** [comment]
@asdliuquan @MartinHero
 `from ..crawler.tradition2simple import traditional2simple`

**Comment by SimmerChan** [comment]
见上
