### ISSUE TITLE
docker build 报错

### ISSUE THREAD

**Issue by qihonggang** [SimmerChan/KG-demo-for-movie#24]
![image](https://user-images.githubusercontent.com/9431724/93503375-8e637400-f94a-11ea-9cea-c5eb121b1cab.png)

**Comment by zhoushaokun** [comment]
同docker报错，后来找了一下原因，发现是因为dos和unix的shell格式问题，做一个[dos2unix的转化](https://www.linuxcool.com/dos2unix)就可以解决，具体的话，我也是刚学了一下docker和linux，感觉最好是改dockerfile文件，做一个转化，或者容器跑起来之后用bash进去，然后再修改 tdbloader start.sh fuseki fuseki-server 的 :set ff=unix，然后再执行./start.sh

**Comment by YongshengWin** [comment]
同问题，用的win的docker，打算装个Ubuntu试一下。想看demo太难啦。

**Comment by zhoushaokun** [comment]
> 同问题，用的win的docker，打算装个Ubuntu试一下。想看demo太难啦。

哈哈哈，我在虚拟机上ubuntu系统试了，貌似也不行，现在我貌似已经基本解决了。把dockerfile修改成下边：
```
FROM ubuntu:16.04

RUN sed -i 's#http://archive.ubuntu.com/#http://mirrors.tuna.tsinghua.edu.cn/#' /etc/apt/sources.list
RUN apt-get update
RUN apt-get install dos2unix 
RUN apt-get -y install vim 
RUN apt-get -y install python-software-properties
RUN apt-get -y install software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt-get update
RUN apt-get -y install python3.6
RUN apt-get -y install python3.6-dev
RUN apt-get -y install default-jdk

ADD . /kbqa
WORKDIR /kbqa

RUN /usr/bin/python3.6 get-pip.py
RUN /usr/local/bin/pip3.6 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ && rm -rf ~/.cache/pip

RUN find /kbqa/jena/apache-jena-3.5.0/bin/ | xargs dos2unix \
  && find /kbqa/jena/apache-jena-fuseki-3.5.0/bin/ | xargs dos2unix \
  && dos2unix /kbqa/jena/apache-jena-fuseki-3.5.0/fuseki \
  && dos2unix /kbqa/jena/apache-jena-fuseki-3.5.0/fuseki-server
RUN /kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 STREAMLIT_SERVER_PORT=80 FUSEKI_HOME=/kbqa/jena/apache-jena-fuseki-3.5.0

EXPOSE 80

CMD ["./start.sh"]
```
然后重新 `docker build -t kbqa:V0.1 .`一下。
**或者**，直接拉我上传的[镜像](https://hub.docker.com/repository/docker/isikies/kgdemo/tags?page=1)，应该也可以

**Comment by zhoushaokun** [comment]
顺便将 start.sh 改了，然后也不会出现README.md中所说的问题，
```
rm -f ./jena/tdb/*
/kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"
streamlit run /kbqa/streamlit_app.py --server.enableCORS=true &
cd /kbqa/jena/apache-jena-fuseki-3.5.0 || return
./fuseki-server
```
在[v1.3](https://hub.docker.com/r/isikies/kgdemo)已经修改

**Comment by YongshengWin** [comment]
> 顺便将 start.sh 改了，然后也不会出现README.md中所说的问题，
> 
> ```
> rm -f ./jena/tdb/*
> /kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"
> streamlit run /kbqa/streamlit_app.py --server.enableCORS=true &
> cd /kbqa/jena/apache-jena-fuseki-3.5.0 || return
> ./fuseki-server
> ```
> 
> 在[v1.3](https://hub.docker.com/r/isikies/kgdemo)已经修改

请问拉完您的镜像之后浏览器端口是什么呢？

**Comment by zhoushaokun** [comment]
> > 顺便将 start.sh 改了，然后也不会出现README.md中所说的问题，
> > ```
> > rm -f ./jena/tdb/*
> > /kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"
> > streamlit run /kbqa/streamlit_app.py --server.enableCORS=true &
> > cd /kbqa/jena/apache-jena-fuseki-3.5.0 || return
> > ./fuseki-server
> > ```
> > 
> > 
> > 在[v1.3](https://hub.docker.com/r/isikies/kgdemo)已经修改
> 
> 请问拉完您的镜像之后浏览器端口是什么呢？

输 localhost 就可以

**Comment by YongshengWin** [comment]
> > > 顺便将 start.sh 改了，然后也不会出现README.md中所说的问题，
> > > ```
> > > rm -f ./jena/tdb/*
> > > /kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"
> > > streamlit run /kbqa/streamlit_app.py --server.enableCORS=true &
> > > cd /kbqa/jena/apache-jena-fuseki-3.5.0 || return
> > > ./fuseki-server
> > > ```
> > > 
> > > 
> > > 在[v1.3](https://hub.docker.com/r/isikies/kgdemo)已经修改
> > 
> > 
> > 请问拉完您的镜像之后浏览器端口是什么呢？
> 
> 输 localhost 就可以

`root@7195c94398a5:/kbqa# bash start.sh
07:08:41 INFO  loader               :: -- Start triples data phase
07:08:41 INFO  loader               :: ** Load empty triples table
07:08:41 INFO  loader               :: -- Start quads data phase
07:08:41 INFO  loader               :: ** Load empty quads table
07:08:41 INFO  loader               :: Load: /kbqa/kg_demo_movie.nt -- 2020/09/30 07:08:41 UTC
07:08:43 INFO  loader               :: -- Finish triples data phase
07:08:43 INFO  loader               :: ** Data: 47,144 triples loaded in 1.56 seconds [Rate: 30,259.31 per second]
07:08:43 INFO  loader               :: -- Finish quads data phase
07:08:43 INFO  loader               :: -- Start triples index phase
07:08:43 INFO  loader               :: ** Index SPO->POS: 47,144 slots indexed in 0.20 seconds [Rate: 239,309.64 per second]
07:08:43 INFO  loader               :: ** Index SPO->OSP: 47,144 slots indexed in 0.16 seconds [Rate: 291,012.34 per second]
07:08:43 INFO  loader               :: -- Finish triples index phase
07:08:43 INFO  loader               :: ** 47,144 triples indexed in 0.37 seconds [Rate: 129,161.64 per second]
07:08:43 INFO  loader               :: -- Finish triples load
07:08:43 INFO  loader               :: ** Completed: 47,144 triples loaded in 1.93 seconds [Rate: 24,414.29 per second]
07:08:43 INFO  loader               :: -- Finish quads load
[2020-09-30 07:08:45] Server     INFO  Apache Jena Fuseki 3.5.0
[2020-09-30 07:08:45] Config     INFO  FUSEKI_HOME=/kbqa/jena/apache-jena-fuseki-3.5.0
[2020-09-30 07:08:45] Config     INFO  FUSEKI_BASE=/kbqa/jena/apache-jena-fuseki-3.5.0/run
[2020-09-30 07:08:45] Config     INFO  Shiro file: file:///kbqa/jena/apache-jena-fuseki-3.5.0/run/shiro.ini
[2020-09-30 07:08:45] Config     INFO  Configuration file: /kbqa/jena/apache-jena-fuseki-3.5.0/run/config.ttl
[2020-09-30 07:08:45] Config     INFO  Load configuration: file:///kbqa/jena/apache-jena-fuseki-3.5.0/run/configuration/fuseki_conf.ttl
Building prefix dict from the default dictionary ...
2020-09-30 07:08:45.919 Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
2020-09-30 07:08:45.923 Loading model from cache /tmp/jieba.cache

  You can now view your Streamlit app in your browser.

  Network URL: http://172.17.0.2:80
  External URL: http://221.6.40.192:80

[2020-09-30 07:08:46] Config     INFO  Register: /kg_demo_movie
[2020-09-30 07:08:46] Server     INFO  Started 2020/09/30 07:08:46 UTC on port 3030
Loading model cost 0.856 seconds.
2020-09-30 07:08:46.776 Loading model cost 0.856 seconds.
Prefix dict has been built successfully.
2020-09-30 07:08:46.777 Prefix dict has been built successfully.`

请问我这里哪里出错了么？我的localhost还是不行

**Comment by zhoushaokun** [comment]
> > > > 顺便将 start.sh 改了，然后也不会出现README.md中所说的问题，
> > > > ```
> > > > rm -f ./jena/tdb/*
> > > > /kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"
> > > > streamlit run /kbqa/streamlit_app.py --server.enableCORS=true &
> > > > cd /kbqa/jena/apache-jena-fuseki-3.5.0 || return
> > > > ./fuseki-server
> > > > ```
> > > > 
> > > > 
> > > > 在[v1.3](https://hub.docker.com/r/isikies/kgdemo)已经修改
> > > 
> > > 
> > > 请问拉完您的镜像之后浏览器端口是什么呢？
> > 
> > 
> > 输 localhost 就可以
> 
> `root@7195c94398a5:/kbqa# bash start.sh
> 07:08:41 INFO loader :: -- Start triples data phase
> 07:08:41 INFO loader :: ** Load empty triples table
> 07:08:41 INFO loader :: -- Start quads data phase
> 07:08:41 INFO loader :: ** Load empty quads table
> 07:08:41 INFO loader :: Load: /kbqa/kg_demo_movie.nt -- 2020/09/30 07:08:41 UTC
> 07:08:43 INFO loader :: -- Finish triples data phase
> 07:08:43 INFO loader :: ** Data: 47,144 triples loaded in 1.56 seconds [Rate: 30,259.31 per second]
> 07:08:43 INFO loader :: -- Finish quads data phase
> 07:08:43 INFO loader :: -- Start triples index phase
> 07:08:43 INFO loader :: ** Index SPO->POS: 47,144 slots indexed in 0.20 seconds [Rate: 239,309.64 per second]
> 07:08:43 INFO loader :: ** Index SPO->OSP: 47,144 slots indexed in 0.16 seconds [Rate: 291,012.34 per second]
> 07:08:43 INFO loader :: -- Finish triples index phase
> 07:08:43 INFO loader :: ** 47,144 triples indexed in 0.37 seconds [Rate: 129,161.64 per second]
> 07:08:43 INFO loader :: -- Finish triples load
> 07:08:43 INFO loader :: ** Completed: 47,144 triples loaded in 1.93 seconds [Rate: 24,414.29 per second]
> 07:08:43 INFO loader :: -- Finish quads load
> [2020-09-30 07:08:45] Server INFO Apache Jena Fuseki 3.5.0
> [2020-09-30 07:08:45] Config INFO FUSEKI_HOME=/kbqa/jena/apache-jena-fuseki-3.5.0
> [2020-09-30 07:08:45] Config INFO FUSEKI_BASE=/kbqa/jena/apache-jena-fuseki-3.5.0/run
> [2020-09-30 07:08:45] Config INFO Shiro file: file:///kbqa/jena/apache-jena-fuseki-3.5.0/run/shiro.ini
> [2020-09-30 07:08:45] Config INFO Configuration file: /kbqa/jena/apache-jena-fuseki-3.5.0/run/config.ttl
> [2020-09-30 07:08:45] Config INFO Load configuration: file:///kbqa/jena/apache-jena-fuseki-3.5.0/run/configuration/fuseki_conf.ttl
> Building prefix dict from the default dictionary ...
> 2020-09-30 07:08:45.919 Building prefix dict from the default dictionary ...
> Loading model from cache /tmp/jieba.cache
> 2020-09-30 07:08:45.923 Loading model from cache /tmp/jieba.cache
> 
> You can now view your Streamlit app in your browser.
> 
> Network URL: http://172.17.0.2:80
> External URL: http://221.6.40.192:80
> 
> [2020-09-30 07:08:46] Config INFO Register: /kg_demo_movie
> [2020-09-30 07:08:46] Server INFO Started 2020/09/30 07:08:46 UTC on port 3030
> Loading model cost 0.856 seconds.
> 2020-09-30 07:08:46.776 Loading model cost 0.856 seconds.
> Prefix dict has been built successfully.
> 2020-09-30 07:08:46.777 Prefix dict has been built successfully.`
> 
> 请问我这里哪里出错了么？我的localhost还是不行

没问题呀，我跑出来和你一样的，就可以访问localhost，
![image](https://user-images.githubusercontent.com/32841670/94655674-8edc1180-0331-11eb-9fac-4a896e960183.png)

要不换下端口号：`docker run -p 3000:80 <containerid>`，或者`docker run -p 3000:80 -it <containerid> bash`
或者你百度搜搜有 查看本机端口映射的命令行， 试下。

**Comment by YongshengWin** [comment]
> > > > > 顺便将 start.sh 改了，然后也不会出现README.md中所说的问题，
> > > > > ```
> > > > > rm -f ./jena/tdb/*
> > > > > /kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"
> > > > > streamlit run /kbqa/streamlit_app.py --server.enableCORS=true &
> > > > > cd /kbqa/jena/apache-jena-fuseki-3.5.0 || return
> > > > > ./fuseki-server
> > > > > ```
> > > > > 
> > > > > 
> > > > > 在[v1.3](https://hub.docker.com/r/isikies/kgdemo)已经修改
> > > > 
> > > > 
> > > > 请问拉完您的镜像之后浏览器端口是什么呢？
> > > 
> > > 
> > > 输 localhost 就可以
> > 
> > 
> > `root@7195c94398a5:/kbqa# bash start.sh
> > 07:08:41 INFO loader :: -- Start triples data phase
> > 07:08:41 INFO loader :: ** Load empty triples table
> > 07:08:41 INFO loader :: -- Start quads data phase
> > 07:08:41 INFO loader :: ** Load empty quads table
> > 07:08:41 INFO loader :: Load: /kbqa/kg_demo_movie.nt -- 2020/09/30 07:08:41 UTC
> > 07:08:43 INFO loader :: -- Finish triples data phase
> > 07:08:43 INFO loader :: ** Data: 47,144 triples loaded in 1.56 seconds [Rate: 30,259.31 per second]
> > 07:08:43 INFO loader :: -- Finish quads data phase
> > 07:08:43 INFO loader :: -- Start triples index phase
> > 07:08:43 INFO loader :: ** Index SPO->POS: 47,144 slots indexed in 0.20 seconds [Rate: 239,309.64 per second]
> > 07:08:43 INFO loader :: ** Index SPO->OSP: 47,144 slots indexed in 0.16 seconds [Rate: 291,012.34 per second]
> > 07:08:43 INFO loader :: -- Finish triples index phase
> > 07:08:43 INFO loader :: ** 47,144 triples indexed in 0.37 seconds [Rate: 129,161.64 per second]
> > 07:08:43 INFO loader :: -- Finish triples load
> > 07:08:43 INFO loader :: ** Completed: 47,144 triples loaded in 1.93 seconds [Rate: 24,414.29 per second]
> > 07:08:43 INFO loader :: -- Finish quads load
> > [2020-09-30 07:08:45] Server INFO Apache Jena Fuseki 3.5.0
> > [2020-09-30 07:08:45] Config INFO FUSEKI_HOME=/kbqa/jena/apache-jena-fuseki-3.5.0
> > [2020-09-30 07:08:45] Config INFO FUSEKI_BASE=/kbqa/jena/apache-jena-fuseki-3.5.0/run
> > [2020-09-30 07:08:45] Config INFO Shiro file: file:///kbqa/jena/apache-jena-fuseki-3.5.0/run/shiro.ini
> > [2020-09-30 07:08:45] Config INFO Configuration file: /kbqa/jena/apache-jena-fuseki-3.5.0/run/config.ttl
> > [2020-09-30 07:08:45] Config INFO Load configuration: file:///kbqa/jena/apache-jena-fuseki-3.5.0/run/configuration/fuseki_conf.ttl
> > Building prefix dict from the default dictionary ...
> > 2020-09-30 07:08:45.919 Building prefix dict from the default dictionary ...
> > Loading model from cache /tmp/jieba.cache
> > 2020-09-30 07:08:45.923 Loading model from cache /tmp/jieba.cache
> > You can now view your Streamlit app in your browser.
> > Network URL: http://172.17.0.2:80
> > External URL: http://221.6.40.192:80
> > [2020-09-30 07:08:46] Config INFO Register: /kg_demo_movie
> > [2020-09-30 07:08:46] Server INFO Started 2020/09/30 07:08:46 UTC on port 3030
> > Loading model cost 0.856 seconds.
> > 2020-09-30 07:08:46.776 Loading model cost 0.856 seconds.
> > Prefix dict has been built successfully.
> > 2020-09-30 07:08:46.777 Prefix dict has been built successfully.`
> > 请问我这里哪里出错了么？我的localhost还是不行
> 
> 没问题呀，我跑出来和你一样的，就可以访问localhost，
> ![image](https://user-images.githubusercontent.com/32841670/94655674-8edc1180-0331-11eb-9fac-4a896e960183.png)
> 
> 要不换下端口号：`docker run -p 3000:80 <containerid>`，或者`docker run -p 3000:80 -it <containerid> bash`
> 或者你百度搜搜有 查看本机端口映射的命令行， 试下。

非常感谢！！！！问题已经解决啦！！！！

**Comment by lxy444** [comment]
> > > > > > 顺便将 start.sh 改了，然后也不会出现README.md中所说的问题，
> > > > > > ```
> > > > > > rm -f ./jena/tdb/*
> > > > > > /kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"
> > > > > > streamlit run /kbqa/streamlit_app.py --server.enableCORS=true &
> > > > > > cd /kbqa/jena/apache-jena-fuseki-3.5.0 || return
> > > > > > ./fuseki-server
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > 在[v1.3](https://hub.docker.com/r/isikies/kgdemo)已经修改
> > > > > 
> > > > > 
> > > > > 请问拉完您的镜像之后浏览器端口是什么呢？
> > > > 
> > > > 
> > > > 输 localhost 就可以
> > > 
> > > 
> > > `root@7195c94398a5:/kbqa# bash start.sh 07:08:41 INFO loader :: -- Start triples data phase 07:08:41 INFO loader :: ** Load empty triples table 07:08:41 INFO loader :: -- Start quads data phase 07:08:41 INFO loader :: ** Load empty quads table 07:08:41 INFO loader :: Load: /kbqa/kg_demo_movie.nt -- 2020/09/30 07:08:41 UTC 07:08:43 INFO loader :: -- Finish triples data phase 07:08:43 INFO loader :: ** Data: 47,144 triples loaded in 1.56 seconds [Rate: 30,259.31 per second] 07:08:43 INFO loader :: -- Finish quads data phase 07:08:43 INFO loader :: -- Start triples index phase 07:08:43 INFO loader :: ** Index SPO->POS: 47,144 slots indexed in 0.20 seconds [Rate: 239,309.64 per second] 07:08:43 INFO loader :: ** Index SPO->OSP: 47,144 slots indexed in 0.16 seconds [Rate: 291,012.34 per second] 07:08:43 INFO loader :: -- Finish triples index phase 07:08:43 INFO loader :: ** 47,144 triples indexed in 0.37 seconds [Rate: 129,161.64 per second] 07:08:43 INFO loader :: -- Finish triples load 07:08:43 INFO loader :: ** Completed: 47,144 triples loaded in 1.93 seconds [Rate: 24,414.29 per second] 07:08:43 INFO loader :: -- Finish quads load [2020-09-30 07:08:45] Server INFO Apache Jena Fuseki 3.5.0 [2020-09-30 07:08:45] Config INFO FUSEKI_HOME=/kbqa/jena/apache-jena-fuseki-3.5.0 [2020-09-30 07:08:45] Config INFO FUSEKI_BASE=/kbqa/jena/apache-jena-fuseki-3.5.0/run [2020-09-30 07:08:45] Config INFO Shiro file: file:///kbqa/jena/apache-jena-fuseki-3.5.0/run/shiro.ini [2020-09-30 07:08:45] Config INFO Configuration file: /kbqa/jena/apache-jena-fuseki-3.5.0/run/config.ttl [2020-09-30 07:08:45] Config INFO Load configuration: file:///kbqa/jena/apache-jena-fuseki-3.5.0/run/configuration/fuseki_conf.ttl Building prefix dict from the default dictionary ... 2020-09-30 07:08:45.919 Building prefix dict from the default dictionary ... Loading model from cache /tmp/jieba.cache 2020-09-30 07:08:45.923 Loading model from cache /tmp/jieba.cache You can now view your Streamlit app in your browser. Network URL: http://172.17.0.2:80 External URL: http://221.6.40.192:80 [2020-09-30 07:08:46] Config INFO Register: /kg_demo_movie [2020-09-30 07:08:46] Server INFO Started 2020/09/30 07:08:46 UTC on port 3030 Loading model cost 0.856 seconds. 2020-09-30 07:08:46.776 Loading model cost 0.856 seconds. Prefix dict has been built successfully. 2020-09-30 07:08:46.777 Prefix dict has been built successfully.`
> > > 请问我这里哪里出错了么？我的localhost还是不行
> > 
> > 
> > 没问题呀，我跑出来和你一样的，就可以访问localhost，
> > ![image](https://user-images.githubusercontent.com/32841670/94655674-8edc1180-0331-11eb-9fac-4a896e960183.png)
> > 要不换下端口号：`docker run -p 3000:80 <containerid>`，或者`docker run -p 3000:80 -it <containerid> bash`
> > 或者你百度搜搜有 查看本机端口映射的命令行， 试下。
> 
> 非常感谢！！！！问题已经解决啦！！！！

请问你是怎么解决的呢？我也是浏览器输入了 localhost 之后无反应

**Comment by vcbeaut** [comment]
> > 同问题，用的win的docker，打算装个Ubuntu试一下。想看demo太难啦。
> 
> 哈哈哈，我在虚拟机上ubuntu系统试了，貌似也不行，现在我貌似已经基本解决了。把dockerfile修改成下边：
> 
> ```
> FROM ubuntu:16.04
> 
> RUN sed -i 's#http://archive.ubuntu.com/#http://mirrors.tuna.tsinghua.edu.cn/#' /etc/apt/sources.list
> RUN apt-get update
> RUN apt-get install dos2unix 
> RUN apt-get -y install vim 
> RUN apt-get -y install python-software-properties
> RUN apt-get -y install software-properties-common
> RUN add-apt-repository ppa:deadsnakes/ppa -y
> RUN apt-get update
> RUN apt-get -y install python3.6
> RUN apt-get -y install python3.6-dev
> RUN apt-get -y install default-jdk
> 
> ADD . /kbqa
> WORKDIR /kbqa
> 
> RUN /usr/bin/python3.6 get-pip.py
> RUN /usr/local/bin/pip3.6 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ && rm -rf ~/.cache/pip
> 
> RUN find /kbqa/jena/apache-jena-3.5.0/bin/ | xargs dos2unix \
>   && find /kbqa/jena/apache-jena-fuseki-3.5.0/bin/ | xargs dos2unix \
>   && dos2unix /kbqa/jena/apache-jena-fuseki-3.5.0/fuseki \
>   && dos2unix /kbqa/jena/apache-jena-fuseki-3.5.0/fuseki-server
> RUN /kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"
> 
> ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 STREAMLIT_SERVER_PORT=80 FUSEKI_HOME=/kbqa/jena/apache-jena-fuseki-3.5.0
> 
> EXPOSE 80
> 
> CMD ["./start.sh"]
> ```
> 
> 然后重新 `docker build -t kbqa:V0.1 .`一下。
> **或者**，直接拉我上传的[镜像](https://hub.docker.com/repository/docker/isikies/kgdemo/tags?page=1)，应该也可以

您好，您的镜像运行fuseki-server会报错，可以请问是什么原因嘛？


DatasetPrefixesTDB WARN  Mangled prefix map: graph name=
java.lang.NullPointerException
	at org.apache.jena.tdb.store.DatasetPrefixesTDB.readPrefixMap(DatasetPrefixesTDB.java:117)
	at org.apache.jena.sparql.graph.GraphPrefixesProjection.getNsPrefixMap(GraphPrefixesProjection.java:68)

**Comment by zhoushaokun** [comment]
> > > 同问题，用的win的docker，打算装个Ubuntu试一下。想看demo太难啦。
> > 
> > 
> > 哈哈哈，我在虚拟机上ubuntu系统试了，貌似也不行，现在我貌似已经基本解决了。把dockerfile修改成下边：
> > ```
> > FROM ubuntu:16.04
> > 
> > RUN sed -i 's#http://archive.ubuntu.com/#http://mirrors.tuna.tsinghua.edu.cn/#' /etc/apt/sources.list
> > RUN apt-get update
> > RUN apt-get install dos2unix 
> > RUN apt-get -y install vim 
> > RUN apt-get -y install python-software-properties
> > RUN apt-get -y install software-properties-common
> > RUN add-apt-repository ppa:deadsnakes/ppa -y
> > RUN apt-get update
> > RUN apt-get -y install python3.6
> > RUN apt-get -y install python3.6-dev
> > RUN apt-get -y install default-jdk
> > 
> > ADD . /kbqa
> > WORKDIR /kbqa
> > 
> > RUN /usr/bin/python3.6 get-pip.py
> > RUN /usr/local/bin/pip3.6 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ && rm -rf ~/.cache/pip
> > 
> > RUN find /kbqa/jena/apache-jena-3.5.0/bin/ | xargs dos2unix \
> >   && find /kbqa/jena/apache-jena-fuseki-3.5.0/bin/ | xargs dos2unix \
> >   && dos2unix /kbqa/jena/apache-jena-fuseki-3.5.0/fuseki \
> >   && dos2unix /kbqa/jena/apache-jena-fuseki-3.5.0/fuseki-server
> > RUN /kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"
> > 
> > ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 STREAMLIT_SERVER_PORT=80 FUSEKI_HOME=/kbqa/jena/apache-jena-fuseki-3.5.0
> > 
> > EXPOSE 80
> > 
> > CMD ["./start.sh"]
> > ```
> > 
> > 
> > 然后重新 `docker build -t kbqa:V0.1 .`一下。
> > **或者**，直接拉我上传的[镜像](https://hub.docker.com/repository/docker/isikies/kgdemo/tags?page=1)，应该也可以
> 
> 您好，您的镜像运行fuseki-server会报错，可以请问是什么原因嘛？
> 
> DatasetPrefixesTDB WARN Mangled prefix map: graph name=
> java.lang.NullPointerException
> at org.apache.jena.tdb.store.DatasetPrefixesTDB.readPrefixMap(DatasetPrefixesTDB.java:117)
> at org.apache.jena.sparql.graph.GraphPrefixesProjection.getNsPrefixMap(GraphPrefixesProjection.java:68)

用的`docker pull isikies/kgdemo:v1.3`这个1.3的吗？

**Comment by weidey** [comment]
> > > > 同问题，用的win的docker，打算装个Ubuntu试一下。想看demo太难啦。
> > > 
> > > 
> > > 哈哈哈，我在虚拟机上ubuntu系统试了，貌似也不行，现在我貌似已经基本解决了。把dockerfile修改成下边：
> > > ```
> > > FROM ubuntu:16.04
> > > 
> > > RUN sed -i 's#http://archive.ubuntu.com/#http://mirrors.tuna.tsinghua.edu.cn/#' /etc/apt/sources.list
> > > RUN apt-get update
> > > RUN apt-get install dos2unix 
> > > RUN apt-get -y install vim 
> > > RUN apt-get -y install python-software-properties
> > > RUN apt-get -y install software-properties-common
> > > RUN add-apt-repository ppa:deadsnakes/ppa -y
> > > RUN apt-get update
> > > RUN apt-get -y install python3.6
> > > RUN apt-get -y install python3.6-dev
> > > RUN apt-get -y install default-jdk
> > > 
> > > ADD . /kbqa
> > > WORKDIR /kbqa
> > > 
> > > RUN /usr/bin/python3.6 get-pip.py
> > > RUN /usr/local/bin/pip3.6 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ && rm -rf ~/.cache/pip
> > > 
> > > RUN find /kbqa/jena/apache-jena-3.5.0/bin/ | xargs dos2unix \
> > >   && find /kbqa/jena/apache-jena-fuseki-3.5.0/bin/ | xargs dos2unix \
> > >   && dos2unix /kbqa/jena/apache-jena-fuseki-3.5.0/fuseki \
> > >   && dos2unix /kbqa/jena/apache-jena-fuseki-3.5.0/fuseki-server
> > > RUN /kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"
> > > 
> > > ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 STREAMLIT_SERVER_PORT=80 FUSEKI_HOME=/kbqa/jena/apache-jena-fuseki-3.5.0
> > > 
> > > EXPOSE 80
> > > 
> > > CMD ["./start.sh"]
> > > ```
> > > 
> > > 
> > > 然后重新 `docker build -t kbqa:V0.1 .`一下。
> > > **或者**，直接拉我上传的[镜像](https://hub.docker.com/repository/docker/isikies/kgdemo/tags?page=1)，应该也可以
> > 
> > 
> > 您好，您的镜像运行fuseki-server会报错，可以请问是什么原因嘛？
> > DatasetPrefixesTDB WARN Mangled prefix map: graph name=
> > java.lang.NullPointerException
> > at org.apache.jena.tdb.store.DatasetPrefixesTDB.readPrefixMap(DatasetPrefixesTDB.java:117)
> > at org.apache.jena.sparql.graph.GraphPrefixesProjection.getNsPrefixMap(GraphPrefixesProjection.java:68)
> 
> 用的`docker pull isikies/kgdemo:v1.3`这个1.3的吗？

![image](https://user-images.githubusercontent.com/33025060/110235490-39083700-7f6b-11eb-8d7c-790590d3e638.png)
 为什么输入给出的URL无法打开呀？

报错：Unable to round-trip http request to upstream: dial tcp 172.17.0.2:80: i/o timeout

**Comment by YongshengWin** [comment]
> > > > 同问题，用的win的docker，打算装个Ubuntu试一下。想看demo太难啦。
> > > 
> > > 
> > > 哈哈哈，我在虚拟机上ubuntu系统试了，貌似也不行，现在我貌似已经基本解决了。把dockerfile修改成下边：
> > > ```
> > > FROM ubuntu:16.04
> > > 
> > > RUN sed -i 's#http://archive.ubuntu.com/#http://mirrors.tuna.tsinghua.edu.cn/#' /etc/apt/sources.list
> > > RUN apt-get update
> > > RUN apt-get install dos2unix 
> > > RUN apt-get -y install vim 
> > > RUN apt-get -y install python-software-properties
> > > RUN apt-get -y install software-properties-common
> > > RUN add-apt-repository ppa:deadsnakes/ppa -y
> > > RUN apt-get update
> > > RUN apt-get -y install python3.6
> > > RUN apt-get -y install python3.6-dev
> > > RUN apt-get -y install default-jdk
> > > 
> > > ADD . /kbqa
> > > WORKDIR /kbqa
> > > 
> > > RUN /usr/bin/python3.6 get-pip.py
> > > RUN /usr/local/bin/pip3.6 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ && rm -rf ~/.cache/pip
> > > 
> > > RUN find /kbqa/jena/apache-jena-3.5.0/bin/ | xargs dos2unix \
> > >   && find /kbqa/jena/apache-jena-fuseki-3.5.0/bin/ | xargs dos2unix \
> > >   && dos2unix /kbqa/jena/apache-jena-fuseki-3.5.0/fuseki \
> > >   && dos2unix /kbqa/jena/apache-jena-fuseki-3.5.0/fuseki-server
> > > RUN /kbqa/jena/apache-jena-3.5.0/bin/tdbloader --loc="/kbqa/jena/tdb" "/kbqa/kg_demo_movie.nt"
> > > 
> > > ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 STREAMLIT_SERVER_PORT=80 FUSEKI_HOME=/kbqa/jena/apache-jena-fuseki-3.5.0
> > > 
> > > EXPOSE 80
> > > 
> > > CMD ["./start.sh"]
> > > ```
> > > 
> > > 
> > > 然后重新 `docker build -t kbqa:V0.1 .`一下。
> > > **或者**，直接拉我上传的[镜像](https://hub.docker.com/repository/docker/isikies/kgdemo/tags?page=1)，应该也可以
> > 
> > 
> > 您好，您的镜像运行fuseki-server会报错，可以请问是什么原因嘛？
> > DatasetPrefixesTDB WARN Mangled prefix map: graph name=
> > java.lang.NullPointerException
> > at org.apache.jena.tdb.store.DatasetPrefixesTDB.readPrefixMap(DatasetPrefixesTDB.java:117)
> > at org.apache.jena.sparql.graph.GraphPrefixesProjection.getNsPrefixMap(GraphPrefixesProjection.java:68)
> 
> 用的`docker pull isikies/kgdemo:v1.3`这个1.3的吗？

是的

**Comment by zulihit** [comment]
[](https://user-images.githubusercontent.com/68625084/159836482-d3a099d4-6d68-457b-b734-af538c1f95ed.png)请问，我在ubuntu的终端输入docker build -t kbqa:V0.1 .后报错如下

image
请问这个怎么解决呢
我是第一次使用docker,感谢

**Comment by zulihit** [comment]
> 
![image](https://user-images.githubusercontent.com/68625084/159838348-cbac9241-17d4-4493-8fec-514ef79bd674.png)

**Comment by zhoushaokun** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/68625084/159838348-cbac9241-17d4-4493-8fec-514ef79bd674.png)

执行一下 apt update
