### ISSUE TITLE
docker无法正常使用

### ISSUE THREAD

**Issue by Henry-Avery** [SimmerChan/KG-demo-for-movie#32]
，降低了refo的版本，成功build，网页输入localhost打开后Streamlit报错
ModuleNotFoundError: No module named 'match'
Traceback:
File "/usr/local/lib/python3.6/dist-packages/streamlit/script_runner.py", line 324, in _run_script
    exec(code, module.__dict__)
File "/kbqa/streamlit_app.py", line 2, in <module>
    from kg_demo_movie.KB_query.query_main import QAInterface
File "/kbqa/kg_demo_movie/KB_query/query_main.py", line 16, in <module>
    from kg_demo_movie.KB_query import jena_sparql_endpoint, question2sparql
File "/kbqa/kg_demo_movie/KB_query/question2sparql.py", line 16, in <module>
    from kg_demo_movie.KB_query import question_temp, word_tagging
File "/kbqa/kg_demo_movie/KB_query/question_temp.py", line 29, in <module>
    from refo import finditer, Predicate, Star, Any, Disjunction
File "/usr/local/lib/python3.6/dist-packages/refo/__init__.py", line 8, in <module>
    from match import match, search, finditer

好像是refo版本的问题

**Comment by Henry-Avery** [comment]
直接docker build报错如下，导致原因是“#18 3.463   error in REfO setup command: use_2to3 is invalid.”。之前作者是使用的python2.7，后来更新到了3.6版本，由于python2和python3是两个玩意，导致出现了这些问题。


[+] Building 18.4s (18/19)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:16.04                                                    5.3s
 => [ 1/15] FROM docker.io/library/ubuntu:16.04@sha256:0f71fa8d4d2d4292c3c617fda2b36f6dabe5c8b6e34c3dc5b0d17d4e70  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 38.19kB                                                                               0.1s
 => CACHED [ 2/15] RUN sed -i 's#http://archive.ubuntu.com/#http://mirrors.tuna.tsinghua.edu.cn/#' /etc/apt/sourc  0.0s
 => CACHED [ 3/15] RUN apt-get update                                                                              0.0s
 => CACHED [ 4/15] RUN apt-get -y install python-software-properties                                               0.0s
 => CACHED [ 5/15] RUN apt-get -y install software-properties-common                                               0.0s
 => CACHED [ 6/15] RUN add-apt-repository ppa:deadsnakes/ppa -y                                                    0.0s
 => CACHED [ 7/15] RUN apt-get update                                                                              0.0s
 => CACHED [ 8/15] RUN apt-get -y install python3.6                                                                0.0s
 => CACHED [ 9/15] RUN apt-get -y install python3.6-dev                                                            0.0s
 => CACHED [10/15] RUN apt-get -y install default-jdk                                                              0.0s
 => [11/15] ADD . /kbqa                                                                                            0.4s
 => [12/15] WORKDIR /kbqa                                                                                          0.0s
 => [13/15] RUN /usr/bin/python3.6 get-pip.py                                                                      8.7s
 => ERROR [14/15] RUN /usr/local/bin/pip3.6 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simp  3.6s
------
 > [14/15] RUN /usr/local/bin/pip3.6 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ && rm -rf ~/.cache/pip:
#18 1.335 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
#18 2.133 Collecting refo==0.13
#18 2.189   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/51/b1/fe3af8c96aa634a9502bec5622aadc2e27880843a1da2c5869435772b075/REfO-0.13.tar.gz (12 kB)
#18 2.225   Preparing metadata (setup.py): started
#18 3.463   Preparing metadata (setup.py): finished with status 'error'
#18 3.463   ERROR: Command errored out with exit status 1:
#18 3.463    command: /usr/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wl3sknz9/refo_3278f3ad7ea14cdabe25ec87b0a77d0c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wl3sknz9/refo_3278f3ad7ea14cdabe25ec87b0a77d0c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xc0v_fg3
#18 3.463        cwd: /tmp/pip-install-wl3sknz9/refo_3278f3ad7ea14cdabe25ec87b0a77d0c/
#18 3.463   Complete output (27 lines):
#18 3.463   warning: no files found matching 'ez_setup.py'
#18 3.463   warning: no previously-included files matching '*.pyc' found anywhere in distribution
#18 3.463   warning: no previously-included files matching '*$py.class' found anywhere in distribution
#18 3.463   creating build
#18 3.463   creating build/src
#18 3.463   creating build/src/examples
#18 3.463   creating build/src/refo
#18 3.463   creating build/src/tests
#18 3.463   copying README.txt -> build/src
#18 3.463   copying requirements.txt -> build/src
#18 3.463   copying LICENSE.txt -> build/src
#18 3.463   copying README.md -> build/src
#18 3.463   copying refo/match.py -> build/src/refo
#18 3.463   copying refo/virtualmachine.py -> build/src/refo
#18 3.463   copying refo/patterns.py -> build/src/refo
#18 3.463   copying refo/instructions.py -> build/src/refo
#18 3.463   copying refo/__init__.py -> build/src/refo
#18 3.463   copying examples/path.py -> build/src/examples
#18 3.463   copying examples/words.py -> build/src/examples
#18 3.463   copying examples/xml_reader.py -> build/src/examples
#18 3.463   copying examples/poly_time.py -> build/src/examples
#18 3.463   copying tests/test_refo.py -> build/src/tests
#18 3.463   Skipping optional fixer: buffer
#18 3.463   Skipping optional fixer: idioms
#18 3.463   Skipping optional fixer: set_literal
#18 3.463   Skipping optional fixer: ws_comma
#18 3.463   error in REfO setup command: use_2to3 is invalid.
#18 3.463   ----------------------------------------
#18 3.464 WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/51/b1/fe3af8c96aa634a9502bec5622aadc2e27880843a1da2c5869435772b075/REfO-0.13.tar.gz#sha256=f5c9fd5d6ae083b15071a27ebdf02353c7af9ecc92e22b67f961ecdf5e0355f4 (from https://pypi.tuna.tsinghua.edu.cn/simple/refo/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#18 3.464 ERROR: Could not find a version that satisfies the requirement refo==0.13 (from versions: 0.1, 0.11, 0.12, 0.13)
#18 3.465 ERROR: No matching distribution found for refo==0.13
------
executor failed running [/bin/sh -c /usr/local/bin/pip3.6 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ && rm -rf ~/.cache/pip]: exit code: 1

**Comment by dong-tc** [comment]
这个问题请问现在解决了吗，python版本一直换不明白

**Comment by Log4J-Ops** [comment]
请问现在解决了吗，我也遇到了这个问题，改python版本没有用

**Comment by SimmerChan** [comment]
我已收到您的邮件，祝您生活愉快！

**Comment by Henry-Avery** [comment]
> 请问现在解决了吗，我也遇到了这个问题，改python版本没有用

并没有，我已经更换项目了，花了不少时间查资料发现没法解决有些库版本的问题

**Comment by log5j** [comment]
好吧，我也发现这个问题很难办，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月11日(周六) 晚上8:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SimmerChan/KG-demo-for-movie] docker无法正常使用 (Issue #32)




  
请问现在解决了吗，我也遇到了这个问题，改python版本没有用
  
并没有，我已经更换项目了，花了不少时间查资料发现没法解决有些库版本的问题
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Log4J-Ops** [comment]
> > 请问现在解决了吗，我也遇到了这个问题，改python版本没有用
> 
> 并没有，我已经更换项目了，花了不少时间查资料发现没法解决有些库版本的问题

好吧，我也发现这是个难题，感谢
