### ISSUE TITLE
WARN  JettyLauncher

### ISSUE THREAD

**Issue by king33yoyo** [SimmerChan/KG-demo-for-movie#8]
您好：

我在运行
`d2r-server.bat` kg_demo_movie_mapping.ttl
时，报错

>  Database connection to jdbc:mysql:///kg_demo_movie failed (user: root): Could not
 create connection to database server. Attempted reconnect 3 times. Giving up. (E54)

![image](https://user-images.githubusercontent.com/18387267/41947215-e994625a-79e8-11e8-8b9d-d93ef60eff64.png)

我的mysql服务已经启动了，系统是windows。
刚接触这一领域，java也不太熟悉，希望得到你的指教。

**Comment by king33yoyo** [comment]
数据库也已经导入了。是否是因为java环境的问题？如何排查？

**Comment by SimmerChan** [comment]
@king33yoyo 看是不是JDBC的问题，如果是，参考http://d2rq.org/getting-started配置。
