### ISSUE TITLE
Fuseki启动时报TDBException

### ISSUE THREAD

**Issue by lhzxxy** [SimmerChan/KG-demo-for-movie#9]
您好，我是在知乎上看到您写的语义网的文章的，我也在学习语义网相关的知识，看了之后感觉很有用。但是在动手做您上面的例子时却有问题。实践篇（四）里面，按照您说的配置好之后，启动Fuseki时却报错了。试了很多次，每一步都是按您说的做的，但是还是有问题，很迷惑，希望您帮助我一下。

![image](https://user-images.githubusercontent.com/39483165/42133929-bfa40084-7d64-11e8-96e8-db3dbf7f7cad.png)

![image](https://user-images.githubusercontent.com/39483165/42133906-52998ba8-7d64-11e8-901e-727db0ef5a28.png)

**Comment by SimmerChan** [comment]
@lhzxxy 看报的错是文件的读写权限有问题，你重新新建这个文件试试呢？

**Comment by lhzxxy** [comment]
@SimmerChan 您好，我发现把ja:content [ja:externalContent <file:///D:/SemanticWeb/apache-jena-fuseki-3.8.0/run/databases/ontology.ttl> ] ;注释掉之后就不会报错了，但是这样就没有hasActor的推理能力了。

**Comment by lhzxxy** [comment]
@foreverTracy 试一下下面这个：
  <#tdb_dataset_readwrite> rdf:type       ja:RDFDataset ;

    ja:defaultGraph       <#model_inf_2> ;
     .
  <#model_inf_2> rdfs:label "Inf-2" ;
    ja:baseModel 
        [ a ja:MemoryModel ;
          ja:content [ja:externalContent <file:///D:/SemanticWeb/apache-jena-fuseki-3.8.0/run/databases/ontology.ttl>] ;
        ] ;
    ja:reasoner [
        ja:reasonerURL <http://jena.hpl.hp.com/2003/OWLFBRuleReasoner> ;
		]		
    .

**Comment by foreverTracy** [comment]
@lhzxxy 还是不行啊。。。你这样做通过了吗

**Comment by lhzxxy** [comment]
@foreverTracy 我一开始是按他在知乎上的步骤配置的，然后启动报错，接着改成这样就会推理了。

**Comment by lhzxxy** [comment]
@foreverTracy 整个文件是这样的：
@prefix :      <http://base/#> .
@prefix tdb:   <http://jena.hpl.hp.com/2008/tdb#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix ja:    <http://jena.hpl.hp.com/2005/11/Assembler#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix fuseki: <http://jena.apache.org/fuseki#> .


:service1        a                fuseki:Service ;
fuseki:dataset                    <#tdb_dataset_readwrite> ;
fuseki:name                       "kg_demo_movie" ;
fuseki:serviceQuery               "query" , "sparql" ;
fuseki:serviceReadGraphStore      "get" ;
fuseki:serviceReadWriteGraphStore "data" ;
fuseki:serviceUpdate              "update" ;
fuseki:serviceUpload              "upload" .


  <#tdb_dataset_readwrite> rdf:type       ja:RDFDataset ;

    ja:defaultGraph       <#model_inf_2> ;
     .
  <#model_inf_2> rdfs:label "Inf-2" ;
    ja:baseModel 
        [ a ja:MemoryModel ;
          ja:content [ja:externalContent <file:///D:/SemanticWeb/apache-jena-fuseki-3.8.0/run/databases/ontology.ttl>] ;
        ] ;
    ja:reasoner [
        ja:reasonerURL <http://jena.hpl.hp.com/2003/OWLFBRuleReasoner> ;
		]		
    .

**Comment by BigBrother5** [comment]
@lhzxxy 

但是这样配置的话，就不是TDB存储了，你指定的是MemoryModel，每次 fuseki 服务器重启数据就没有了！ 3.5.0 SimmerChan的配置是可以的，但是3.8.0不行，应该是版本更新导致的问题吧

**Comment by lhzxxy** [comment]
@BigBrother5 
嗯嗯，这样做每次重启都要再上传数据，挺麻烦的。我也觉得应该是版本的原因，谢谢告知~~

**Comment by achuanggo** [comment]
3.5.0是正解啊，3.8就会报这个错

**Comment by Lip136** [comment]
@lhzxxy 不知道你解决了没有，我现在可以加入TDB数据，但是本体推理和规则都没办法加进去。

**Comment by tangg555** [comment]
您好博主，我也是3.8总是报错，想下载3.5的安装包但是却发现官网不提供老版本的下载，请问能分享下jena 和 fuseki安装包的链接吗

**Comment by SimmerChan** [comment]
@tangg555 3.8不兼容 3.7可以，官网有[历史版本](http://archive.apache.org/dist/jena/binaries/)下载

**Comment by tangg555** [comment]
非常感谢！

**Comment by tangg555** [comment]
再次打扰了博主_(:з」∠)_
![ob_acavdjute topul xe r](https://user-images.githubusercontent.com/22412972/45911984-396cf000-be4d-11e8-8e5f-256e569c39fb.png)
![n8ih6q 61 9uqayro2ibn 7](https://user-images.githubusercontent.com/22412972/45911987-45f14880-be4d-11e8-9512-a8373c656588.png)
但是用sparql查的时候却查不到数据，我看了下fuseki服务器上的数据
![wnd6js6niv 81 h wj4kq r](https://user-images.githubusercontent.com/22412972/45912013-b4360b00-be4d-11e8-8a80-eca15482996f.png)
有点懵....不知道哪个环节出了问题，我的配置文件是这样的：
@prefix :      <http://base/#> .
@prefix tdb:   <http://jena.hpl.hp.com/2008/tdb#> .
@prefix tdb2:  <http://jena.apache.org/2016/tdb#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix ja:    <http://jena.hpl.hp.com/2005/11/Assembler#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix fuseki: <http://jena.apache.org/fuseki#> .


:service1        a                fuseki:Service ;
fuseki:dataset                    <#dataset> ;
fuseki:name                       "kg_demo_movie" ;
fuseki:serviceQuery               "query" , "sparql" ;
fuseki:serviceReadGraphStore      "get" ;
fuseki:serviceReadWriteGraphStore "data" ;
fuseki:serviceUpdate              "update" ;
fuseki:serviceUpload              "upload" .


<#dataset> rdf:type ja:RDFDataset ;
    ja:defaultGraph <#model_inf> ;
    .

<#model_inf> a ja:InfModel ;
    ja:baseModel <#tdbGraph> ;

    #本体文件的路径
    # ja:content [ja:externalContent <file:///D:/software/Database/apache-jena-fuseki-3.7.0/run/databases/ontology.ttl> ] ;
    
    #关闭OWL推理机
    #ja:reasoner [ja:reasonerURL <http://jena.hpl.hp.com/2003/OWLFBRuleReasoner>] .

    #开启规则推理机，并指定规则文件路径
    ja:reasoner [
        ja:reasonerURL <http://jena.hpl.hp.com/2003/GenericRuleReasoner> ; 
        ja:rulesFrom <file:///D:/software/Database/apache-jena-fuseki-3.7.0/run/databases/rules.ttl> ; ]
    .

<#tdbGraph> rdf:type tdb2:GraphTDB ;
    tdb2:dataset <#tdbDataset> ;
    .

<#tdbDataset> rdf:type tdb2:DatasetTDB ;
    tdb2:location "D:/software/Database/apache-jena-3.7.0/tdb" ;
    .

**Comment by tangg555** [comment]
除此此外，用fuseki在线上传.nt文件是正常的，
![y6zf myhs x d271 xpxv6l](https://user-images.githubusercontent.com/22412972/45912167-ca44cb00-be4f-11e8-918f-a8abe4b1fe29.png)
不知道咋回事，可能jena有毒吧_(:з」∠)_
